### ISSUE TITLE
Cannot run server

### ISSUE THREAD

**Issue by liukewia** [TIGER-H/fakebook#1]
Cannot run server

**Comment by TIGER-H** [comment]
> Cannot run server

用你自己的mongo url

**Comment by liukewia** [comment]
> > Cannot run server
> 
> 用你自己的mongo url

Could you add the configuration in readme?

Or try my [deployed project](https://github.com/liukewia/cookbook)!

**Comment by TIGER-H** [comment]
> > > Cannot run server
> > 
> > 
> > 用你自己的mongo url
> 
> Could you add the configuration in readme?
> 
> Or try my [deployed project](https://github.com/liukewia/cookbook)!

try一点
